[package]
name = "throw-shade"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
cpal = "0.15.3"
raylib = "5.0.2"
rodio = "0.20.1"
rustfft = "6.2.0"
